### ISSUE TITLE
Compatability List

### ISSUE THREAD

**Issue by powerpuffboysz** [Luca1991/DiscCheckEmu#10]
Could you make a compatibility list of games you tested that people can contribute to?

**Comment by Luca1991** [comment]
Hi @powerpuffboysz , thank you very much for your interest in this project.

Surely having a sort of wiki/compatibility list of games and software is a great suggestion and could help DCE users.

This however is out of the scope of this specific repository tho, so a dedicaded repository would be the best solution.

I don't have the required time to create and maintain it, but if someone wants to do create a repo, I'm not against it at all.

Thanks,
Luca

**Comment by Luca1991** [comment]
@powerpuffboysz I decided to create such repo.
Enjoy and please contribute: https://github.com/Luca1991/DCEConfigs

Closing as completed.
