### ISSUE TITLE
Suggestion: Optionally force direct hooking of Kernel32.dll entrypoints

### ISSUE THREAD

**Issue by nckstwrt** [Luca1991/DiscCheckEmu#23]
Sometimes just using GetProcAddress or similar you will get entrypoints to shims rather than Kernel32 itself. Because SafeDisc sometimes iterates through Kernel32.dll to get its addresses for functions, any hooks sometimes are bypassed as DCE is hooking the shim while SafeDisc is calling Kernel32 directly.

I crudely did the following to workaround it for CreateFileA - but it would be nice to have something similar as an option in the YAML rather than maintain my own fork.

```c
DWORD FindRealAddress(const char* szDLLName, const char* szProcName)
{
    DWORD ret = (DWORD)-1L;
    HMODULE lib = LoadLibraryEx(szDLLName, NULL, DONT_RESOLVE_DLL_REFERENCES);
    PIMAGE_NT_HEADERS header = (PIMAGE_NT_HEADERS)((BYTE*)lib + ((PIMAGE_DOS_HEADER)lib)->e_lfanew);
    PIMAGE_EXPORT_DIRECTORY exports = (PIMAGE_EXPORT_DIRECTORY)((BYTE*)lib + header->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_EXPORT].VirtualAddress);
    DWORD* names = (DWORD*)((int)lib + exports->AddressOfNames);
    WORD* ords = (WORD*)((int)lib + exports->AddressOfNameOrdinals);
    DWORD* funcs = (DWORD*)((int)lib + exports->AddressOfFunctions);
    for (DWORD i = 0; i < exports->NumberOfNames; i++)
    {
        if (stricmp(szProcName, (char*)lib + (DWORD)names[i]) == 0)
        {
            // TODO: Worry about Ordinalbase ???
            ret = ((DWORD)lib) + (DWORD)funcs[ords[i]];
            break;
        }
    }
    return ret;
}

void installHooks()
{
    OGCreateFileA = (HANDLE(WINAPI*)(LPCSTR,DWORD,DWORD,LPSECURITY_ATTRIBUTES,DWORD,DWORD,HANDLE))(FindRealAddress("kernel32.dll", "CreateFileA"));

```

**Comment by Luca1991** [comment]
Hi, this is definitely something I want to take a closer look at, but I'm not sure I've understood the problem correctly.
I still have some things I'm working on, so please give me a couple more days and then we can talk about this issue and see what to do.
In the meantime, if you could give me more details, I would really appreciate it!
Thanks for your patience.

**Comment by nckstwrt** [comment]
Hi Luca :)

What I was referring to was the hooking of either compatibility shims or import/export tables (where you have a jmp to the real kernel32 function). SafeDisc bypasses the hooking of those addresses as it iterates over kernel32 to get the real function address and calls that.

However, I wasn't engaging my brain :) As I'm the one loading your DLL I can modify the tables so you hook the "real" functions. So no need to change anything :)

**Comment by Luca1991** [comment]
Perfect👍🏻
